# Site settings
title: Justin Harder's ML Blog
email: justinhardermsc@gmail.com
description: >-
  Justin Harder's blog on machine learning, computer vision, and large language models.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://justintienken-harder.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: your_twitter
github_username:  https://github.com/JustinTienken-Harder

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
#  - jekyll-scholar

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - .idea/

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

scholar:
  style: apa
  locale: en
  sort_by: year
  order: descending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  replace_strings: true
  join_strings: true